[settings]
seed = 1255
n_env = 2

[scenario]
n_agents = 1
n_scripted_entities = 30
episode_size = 1000

[action_space]
low = -10
high = 10
interval = 5

[observation_space]
low = 0
high = 800
shape = [2,2]


[critic_network]
hidden_layers = [64, 32]
activations = ["relu", "relu"]
