[settings]
    seed = 2
    n_env = 8
    dt = 0.05
    record = false

[scenario]
    n_agents = 1
    n_scripted_entities = 5
    episode_size = 500
    agent_radius = 40
    ldr_radius = 160
    prb_radius = 80
    ldr_str = 50
    prb_str = 60
    w_c = 0.5
    w_a = 0.7
    w_s = 1.0
    Kp_l = 2.0
    Kp_p = 0.0

[action_space]
    low = -250
    high = 250
    step = 50

[observation_space]
    low = 0
    high = 800
