[settings]
seed = 6251
n_env = 1

[scenario]
n_agents = 1
n_scripted_entities = 20
episode_size = 2000

[action_space]
low = -100
high = 100
step = 50

[observation_space]
low = 0
high = 800
shape = [2,2]


[critic_network]
hidden_layers = [64, 32]
activations = ["relu", "relu"]
