[settings]
seed = 125
n_env = 1

[scenario]
n_agents = 1
n_scripted_entities = 2
episode_size = 5

[action_space]
low = -10
high = 10
step = 5

[observation_space]
low = 0
high = 800
shape = [2,2]


[critic_network]
hidden_layers = [64, 32]
activations = ["relu", "relu"]
